spring:
  data:
    mongodb:
      uri: "mongodb://${MONGO_USER:candidate_user}:${MONGO_PASSWORD:candidate_password}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:candidate}"

job:
  service:
    url: "${JOB_SERVICE_URL:http://localhost:8082}"